zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - 2181:2181
kafka:
  image: wurstmeister/kafka:0.10.2.1
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CREATE_TOPICS: "test:1:1"
    KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
